package com.rayrobdod.possibleEvolutions

import scala.collection.immutable.SortedMap

object TeachableMoves {
	final case class MoveSet(tms:Seq[String], tutors:Map[String, String])

	lazy val seedData:SortedMap[Run, SortedMap[String, String]] = SortedMap(
		Runs.FireRed -> SortedMap(
			"TM01" -> "Rain Dance",
			"TM02" -> "Muddy Water",
			"TM03" -> "Frustration",
			"TM04" -> "Haze",
			"TM05" -> "Flail",
			"TM06" -> "Pin Missile",
			"TM07" -> "Sand Tomb",
			"TM08" -> "Nature Power",
			"TM09" -> "Guillotine",
			"TM10" -> "Slash",
			"TM11" -> "Endeavor",
			"TM12" -> "Acid Armor",
			"TM13" -> "Snore",
			"TM14" -> "Counter",
			"TM15" -> "Curse",
			"TM16" -> "Iron Tail",
			"TM17" -> "Skill Swap",
			"TM18" -> "Conversion 2",
			"TM19" -> "Sweet Kiss",
			"TM20" -> "Rapid Spin",
			"TM21" -> "Imprison",
			"TM22" -> "Doom Desire",
			"TM23" -> "Spider Web",
			"TM24" -> "Needle Arm",
			"TM25" -> "Sand-Attack",
			"TM26" -> "Thrash",
			"TM27" -> "Reflect",
			"TM28" -> "Will-O-Wisp",
			"TM29" -> "Focus Energy",
			"TM30" -> "Explosion",
			"TM31" -> "Slack Off",
			"TM32" -> "Present",
			"TM33" -> "Fake Out",
			"TM34" -> "Spike Cannon",
			"TM35" -> "Eruption",
			"TM36" -> "Sludge",
			"TM37" -> "Karate Chop",
			"TM38" -> "Teleport",
			"TM39" -> "Crush Claw",
			"TM40" -> "Astonish",
			"TM41" -> "Howl",
			"TM42" -> "Bubblebeam",
			"TM43" -> "Aurora Beam",
			"TM44" -> "Dream Eater",
			"TM45" -> "Horn Drill",
			"TM46" -> "Water Gun",
			"TM47" -> "Metal Claw",
			"TM48" -> "Water Sport",
			"TM49" -> "Softboiled",
			"TM50" -> "Mud-Slap",
			"MEGA PUNCH" -> "Flame Wheel",
			"SWORDS DANCE" -> "Withdraw",
			"MEGA KICK" -> "Doubleslap",
			"BODY SLAM" -> "Sacred Fire",
			"DOUBLE-EDGE" -> "Snatch",
			"COUNTER" -> "Aromatherapy",
			"SEISMIC TOSS" -> "Ember",
			"MIMIC" -> "Signal Beam",
			"METRONOME" -> "Psybeam",
			"SOFTBOILED" -> "Shadow Punch",
			"DREAM EATER" -> "Leer",
			"THUNDER WAVE" -> "Recover",
			"EXPLOSION" -> "Rollout",
			"ROCK SLIDE" -> "Follow Me",
			"SUBSTITUTE" -> "Poison Fang",
		),
		Runs.Platinum -> SortedMap(
			"TM01" -> "Confuse Ray",
			"TM02" -> "Beat Up",
			"TM03" -> "Psycho Shift",
			"TM04" -> "Aqua Tail",
			"TM05" -> "Lick",
			"TM06" -> "Leaf Blade",
			"TM07" -> "Reversal",
			"TM08" -> "Will-O-Wisp",
			"TM09" -> "Hammer Arm",
			"TM10" -> "Swallow",
			"TM11" -> "Skill Swap",
			"TM12" -> "Gunk Shot",
			"TM13" -> "Synthesis",
			"TM14" -> "Spikes",
			"TM15" -> "Discharge",
			"TM16" -> "Lava Plume",
			"TM17" -> "Softboiled",
			"TM18" -> "Teeter Dance",
			"TM19" -> "Petal Dance",
			"TM20" -> "Bite",
			"TM21" -> "Spider Web",
			"TM22" -> "Present",
			"TM23" -> "U-turn",
			"TM24" -> "Eruption",
			"TM25" -> "Confusion",
			"TM26" -> "Attract",
			"TM27" -> "Bug Buzz",
			"TM28" -> "Barrage",
			"TM29" -> "SmellingSalt",
			"TM30" -> "Metal Claw",
			"TM31" -> "Twineedle",
			"TM32" -> "Selfdestruct",
			"TM33" -> "Dizzy Punch",
			"TM34" -> "Focus Blast",
			"TM35" -> "Dark Pulse",
			"TM36" -> "Horn Attack",
			"TM37" -> "Vine Whip",
			"TM38" -> "Water Gun",
			"TM39" -> "Glare",
			"TM40" -> "Hyper Beam",
			"TM41" -> "Tackle",
			"TM42" -> "Sky Attack",
			"TM43" -> "DynamicPunch",
			"TM44" -> "Shadow Punch",
			"TM45" -> "Air Slash",
			"TM46" -> "Icicle Spear",
			"TM47" -> "Judgment",
			"TM48" -> "Brick Break",
			"TM49" -> "Sunny Day",
			"TM50" -> "Overheat",
			"TM51" -> "Flash",
			"TM52" -> "Arm Thrust",
			"TM53" -> "Double Kick",
			"TM54" -> "Nightmare",
			"TM55" -> "Recover",
			"TM56" -> "Aurora Beam",
			"TM57" -> "Water Pulse",
			"TM58" -> "Pay Day",
			"TM59" -> "Bone Club",
			"TM60" -> "Facade",
			"TM61" -> "Odor Sleuth",
			"TM62" -> "Fire Blast",
			"TM63" -> "Last Resort",
			"TM64" -> "Hyper Fang",
			"TM65" -> "Spacial Rend",
			"TM66" -> "Pluck",
			"TM67" -> "Low Kick",
			"TM68" -> "Force Palm",
			"TM69" -> "Signal Beam",
			"TM70" -> "Superpower",
			"TM71" -> "Foresight",
			"TM72" -> "Hyper Voice",
			"TM73" -> "Thief",
			"TM74" -> "Power Gem",
			"TM75" -> "Psychic",
			"TM76" -> "Brave Bird",
			"TM77" -> "Amnesia",
			"TM78" -> "Super Fang",
			"TM79" -> "Heal Bell",
			"TM80" -> "Yawn",
			"TM81" -> "Copycat",
			"TM82" -> "Safeguard",
			"TM83" -> "Crush Grip",
			"TM84" -> "Snatch",
			"TM85" -> "Conversion",
			"TM86" -> "Switcheroo",
			"TM87" -> "Zap Cannon",
			"TM88" -> "Growl",
			"TM89" -> "Embargo",
			"TM90" -> "Bounce",
			"TM91" -> "Captivate",
			"TM92" -> "Return",
			"Dive" -> "Me First",
			"Mud-Slap" -> "Swift",
			"Fury Cutter" -> "Heat Wave",
			"Icy Wind" -> "Rock Blast",
			"Rollout" -> "Barrier",
			"ThunderPunch" -> "Punishment",
			"Fire Punch" -> "Rock Wrecker",
			"Superpower" -> "Follow Me",
			"Ice Punch" -> "Ice Punch",
			"Iron Head" -> "Hail",
			"Aqua Tail" -> "Sand-Attack",
			"Ominous Wind" -> "Silver Wind",
			"Gastro Acid" -> "Trick Room",
			"Snore" -> "Nature Power",
			"Spite" -> "Rollout",
			"Air Cutter" -> "Mud Shot",
			"Helping Hand" -> "Revenge",
			"Endeavor" -> "Leer",
			"Outrage" -> "Power Swap",
			"AncientPower" -> "Fissure",
			"Synthesis" -> "Helping Hand",
			"Signal Beam" -> "Rock Slide",
			"Zen Headbutt" -> "Sludge Bomb",
			"Vacuum Wave" -> "Drain Punch",
			"Earth Power" -> "Heal Block",
			"Gunk Shot" -> "Detect",
			"Twister" -> "Frustration",
			"Seed Bomb" -> "Mega Punch",
			"Iron Defense" -> "Shadow Sneak",
			"Magnet Rise" -> "Substitute",
			"Last Resort" -> "Double Team",
			"Bounce" -> "Swagger",
			"Trick" -> "Hydro Cannon",
			"Heat Wave" -> "Shadow Force",
			"Knock Off" -> "Tailwind",
			"Sucker Punch" -> "Acid",
			"Swift" -> "Whirlpool",
			"Uproar" -> "Endeavor",
		),
		Runs.White2 -> SortedMap(
			"TM01" -> "Twister",
			"TM02" -> "Swagger",
			"TM03" -> "Curse",
			"TM04" -> "Bubble",
			"TM05" -> "Skill Swap",
			"TM06" -> "Cross Chop",
			"TM07" -> "Magma Storm",
			"TM08" -> "Skull Bash",
			"TM09" -> "Water Pulse",
			"TM10" -> "Circle Throw",
			"TM11" -> "Last Resort",
			"TM12" -> "Acid Armor",
			"TM13" -> "Sludge Wave",
			"TM14" -> "Psycho Boost",
			"TM15" -> "Rock Slide",
			"TM16" -> "Heat Wave",
			"TM17" -> "String Shot",
			"TM18" -> "Substitute",
			"TM19" -> "Bolt Strike",
			"TM20" -> "Autotomize",
			"TM21" -> "Lucky Chant",
			"TM22" -> "Confuse Ray",
			"TM23" -> "Minimize",
			"TM24" -> "Kinesis",
			"TM25" -> "Dark Void",
			"TM26" -> "Magic Room",
			"TM27" -> "Cotton Guard",
			"TM28" -> "Dig",
			"TM29" -> "Extreme Speed",
			"TM30" -> "Fire Blast",
			"TM31" -> "Mind Reader",
			"TM32" -> "Magical Leaf",
			"TM33" -> "Sky Uppercut",
			"TM34" -> "Outrage",
			"TM35" -> "Steamroller",
			"TM36" -> "Low Kick",
			"TM37" -> "Will-O-Wisp",
			"TM38" -> "Spark",
			"TM39" -> "Hail",
			"TM40" -> "False Swipe",
			"TM41" -> "Judgment",
			"TM42" -> "Simple Beam",
			"TM43" -> "Sand Tomb",
			"TM44" -> "Focus Energy",
			"TM45" -> "Follow Me",
			"TM46" -> "Sleep Powder",
			"TM47" -> "Spit Up",
			"TM48" -> "Powder Snow",
			"TM49" -> "Acid",
			"TM50" -> "Night Daze",
			"TM51" -> "Poison Tail",
			"TM52" -> "Clear Smog",
			"TM53" -> "Earth Power",
			"TM54" -> "Thunder Shock",
			"TM55" -> "Hydro Cannon",
			"TM56" -> "Smokescreen",
			"TM57" -> "Protect",
			"TM58" -> "Quick Guard",
			"TM59" -> "Wing Attack",
			"TM60" -> "Comet Punch",
			"TM61" -> "Copycat",
			"TM62" -> "Power Trick",
			"TM63" -> "Rollout",
			"TM64" -> "Softboiled",
			"TM65" -> "Megahorn",
			"TM66" -> "Memento",
			"TM67" -> "Dragon Rush",
			"TM68" -> "Aqua Jet",
			"TM69" -> "Trick Room",
			"TM70" -> "Flash",
			"TM71" -> "Headbutt",
			"TM72" -> "Hydro Pump",
			"TM73" -> "Yawn",
			"TM74" -> "Ominous Wind",
			"TM75" -> "Heavy Slam",
			"TM76" -> "Tail Whip",
			"TM77" -> "Leaf Tornado",
			"TM78" -> "Heal Bell",
			"TM79" -> "Healing Wish",
			"TM80" -> "Spite",
			"TM81" -> "Switcheroo",
			"TM82" -> "Magnet Rise",
			"TM83" -> "Wish",
			"TM84" -> "Ally Switch",
			"TM85" -> "Double Hit",
			"TM86" -> "Sky Attack",
			"TM87" -> "Metal Burst",
			"TM88" -> "Natural Gift",
			"TM89" -> "Sunny Day",
			"TM90" -> "ThunderPunch",
			"TM91" -> "Bite",
			"TM92" -> "Vice Grip",
			"TM93" -> "Power Split",
			"TM94" -> "Conversion 2",
			"TM95" -> "Spider Web",
			"Bind" -> "Assurance",
			"Snore" -> "Scald",
			"Knock Off" -> "Pay Day",
			"Synthesis" -> "Mega Drain",
			"Heat Wave" -> "Rock Wrecker",
			"Role Play" -> "Foul Play",
			"Heal Bell" -> "Revenge",
			"Tailwind" -> "Zen Headbutt",
			"Sky Attack" -> "Seed Flare",
			"Pain Split" -> "Aura Sphere",
			"Giga Drain" -> "Aurora Beam",
			"Drain Punch" -> "Fake Out",
			"Roost" -> "Secret Power",
			"Bug Bite" -> "Drain Punch",
			"Covet" -> "Blue Flare",
			"Super Fang" -> "Psychic",
			"Dual Chop" -> "Snarl",
			"Signal Beam" -> "Aqua Ring",
			"Iron Head" -> "SmellingSalt",
			"Seed Bomb" -> "Rage",
			"Drill Run" -> "Wood Hammer",
			"Bounce" -> "Uproar",
			"Low Kick" -> "Drill Run",
			"Gunk Shot" -> "Rock Blast",
			"Uproar" -> "Flame Charge",
			"ThunderPunch" -> "Meteor Mash",
			"Fire Punch" -> "Reflect Type",
			"Ice Punch" -> "Shadow Punch",
			"Gastro Acid" -> "Shadow Claw",
			"Worry Seed" -> "Needle Arm",
			"Spite" -> "Swallow",
			"After You" -> "Gust",
			"Helping Hand" -> "Frenzy Plant",
			"Trick" -> "Miracle Eye",
			"Magic Room" -> "Faint Attack",
			"Wonder Room" -> "Mega Punch",
			"Endeavor" -> "Smog",
			"Outrage" -> "Dragon Tail",
			"Recycle" -> "Flash Cannon",
			"Snatch" -> "Roar of Time",
			"Stealth Rock" -> "Thunderbolt",
			"Sleep Talk" -> "Bide",
			"Skill Swap" -> "Fusion Flare",
			"Magic Coat" -> "Swords Dance",
			"Block" -> "Sucker Punch",
			"Earth Power" -> "Fiery Dance",
			"Foul Play" -> "Thrash",
			"Gravity" -> "Leer",
			"Magnet Rise" -> "Psybeam",
			"Iron Defense" -> "Brick Break",
			"Last Resort" -> "Vacuum Wave",
			"Superpower" -> "Sludge Bomb",
			"Electroweb" -> "Double-Edge",
			"Icy Wind" -> "Lava Plume",
			"Aqua Tail" -> "Head Charge",
			"Dark Pulse" -> "Twineedle",
			"Zen Headbutt" -> "Inferno",
			"Dragon Pulse" -> "Knock Off",
			"Hyper Voice" -> "Signal Beam",
			"Iron Tail" -> "Hurricane",
		),
		Runs.Randy -> SortedMap(
			"TM01" -> "Hold Back",
			"TM02" -> "Psyshock",
			"TM03" -> "Charge",
			"TM04" -> "Aqua Tail",
			"TM05" -> "Heal Order",
			"TM06" -> "Fire Punch",
			"TM07" -> "Mist",
			"TM08" -> "Leech Life",
			"TM09" -> "Defense Curl",
			"TM10" -> "Retaliate",
			"TM11" -> "Sharpen",
			"TM12" -> "Feather Dance",
			"TM13" -> "Dragon Pulse",
			"TM14" -> "Focus Blast",
			"TM15" -> "Secred Sword",
			"TM16" -> "Splash",
			"TM17" -> "Roost",
			"TM18" -> "Skull Bash",
			"TM19" -> "Leech Seed",
			"TM20" -> "Copycat",
			"TM21" -> "Double Hit",
			"TM22" -> "Rock Tomb",
			"TM23" -> "Ancient Power",
			"TM24" -> "Shadow Force",
			"TM25" -> "Uproar",
			"TM26" -> "Sleep Talk",
			"TM27" -> "Grass Pledge",
			"TM28" -> "Thunder Shock",
			"TM29" -> "Extreme Speed",
			"TM30" -> "Vold Switch",
			"TM31" -> "Wonder Room",
			"TM32" -> "Mind Reader",
			"TM33" -> "Gastro Acid",
			"TM34" -> "Frenzy Plant",
			"TM35" -> "Submission",
			"TM36" -> "Peck",
			"TM37" -> "Extrasensory",
			"TM38" -> "Bug Bite",
			"TM39" -> "Dark Pulse",
			"TM40" -> "Karate Chop",
			"TM41" -> "Tail Glow",
			"TM42" -> "Fairy Lock",
			"TM43" -> "Knock Off",
			"TM44" -> "Rock Wrecker",
			"TM45" -> "Camouflage",
			"TM46" -> "Dig",
			"TM47" -> "Last Resort",
			"TM48" -> "Power Trick",
			"TM49" -> "Pursuit",
			"TM50" -> "Mimic",
			"TM51" -> "Curse",
			"TM52" -> "Power Split",
			"TM53" -> "Spite",
			"TM54" -> "Discharge",
			"TM55" -> "Superpower",
			"TM56" -> "Roar",
			"TM57" -> "Fury Cutter",
			"TM58" -> "Fire Fang",
			"TM59" -> "Trick",
			"TM60" -> "Growl",
			"TM61" -> "Bonemerang",
			"TM62" -> "Baby-Doll Eyes",
			"TM63" -> "Horn Attack",
			"TM64" -> "Future Sight",
			"TM65" -> "Smokescreen",
			"TM66" -> "Strength",
			"TM67" -> "Bolt Strike",
			"TM68" -> "Water Pledge",
			"TM69" -> "Poison Sting",
			"TM70" -> "Wild Charge",
			"TM71" -> "Electro Ball",
			"TM72" -> "Steamroller",
			"TM73" -> "Fire Spin",
			"TM74" -> "Sky Uppercut",
			"TM75" -> "Sketch",
			"TM76" -> "Ally Switch",
			"TM77" -> "Mirror Move",
			"TM78" -> "Chatter",
			"TM79" -> "Focus Punch",
			"TM80" -> "Snarl",
			"TM81" -> "Wide Guard",
			"TM82" -> "Present",
			"TM83" -> "Rock Smash",
			"TM84" -> "Sweet Scent",
			"TM85" -> "Earth Power",
			"TM86" -> "Aerial Ace",
			"TM87" -> "Confusion",
			"TM88" -> "Freeze-Dry",
			"TM89" -> "Rest",
			"TM90" -> "Punishment",
			"TM91" -> "Fly",
			"TM92" -> "Leaf Tornado",
			"TM93" -> "Follow Me",
			"TM94" -> "Double Kick",
			"TM95" -> "Icicle Spear",
			"TM96" -> "Iron Defense",
			"TM97" -> "Vice Grip",
			"TM98" -> "Fire Blast",
			"TM99" -> "Gunk Shot",
			"TM100" -> "Grass Whistle",
		),
	)
}
