name: Unit Test
on: [push]
jobs:
  unit_test:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache ivy modules
      uses: actions/cache@v2
      env:
        cache-name: cache-ivy-modules
      with:
        path: ~/.ivy2
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.sbt') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
    - name: sbt update
      run: sbt update
    - name: Run tests
      run: sbt test
